# Config file for DeepForest pytorch module

#cpu workers for data loaders
#Dataloaders
workers: 0
accelerator: auto
batch_size: 8
devices: auto

# Model Architecture
architecture: 'retinanet'
num_classes: 1
nms_thresh: 0.05

# Architecture specific params
retinanet:
    # Non-max supression of overlapping predictions
    score_thresh: 0.1

train:

    csv_file:
    root_dir:

    #Optomizer  initial learning rate
    lr: 0.0005

    #Print loss every n epochs
    epochs: 50
    
    #Useful debugging flag i    n pytorch lightning, set to True to get a single batch of training to test settings.
    fast_dev_run: False

    #pin images to GPU memory for fast training. This depends on GPU size and number of images.
    preload_images: True
    scheduler:
        type:
        params:
            # Common parameters
            T_max: 10
            eta_min: 0.00001
            lr_lambda: "lambda epoch: 0.95 ** epoch"  # For lambdaLR and multiplicativeLR
            step_size: 30  # For stepLR
            gamma: 0.1  # For stepLR, multistepLR, and exponentialLR
            milestones: [50, 100]  # For multistepLR

            # ReduceLROnPlateau parameters (used if type is not explicitly mentioned)
            mode: "min"
            factor: 0.5
            patience: 10
            threshold: 0.00001
            threshold_mode: "rel"
            cooldown: 3
            min_lr: 0.000001
            eps: 0.0000001

validation:
    #callback args
    csv_file:
    root_dir:
    #Intersection over union evaluation
    iou_threshold: 0.4
    val_accuracy_interval: 5
