# A yaml file that contains the configuration for the pipeline

# Remote server for image hosting
user: 'ben'
host: 'serenity.ifas.ufl.edu'
key_filename: '/home/b.weinstein/.ssh/id_rsa.pub'
folder_name: '/pgsql/retrieverdash/everglades-label-studio/everglades-data'

comet_workspace: "bw4sz"
comet_project: "everglades-airplane"

# Model Training
# Model checkpoints are saved in the checkpoint_dir, model_checkpoint is the path to the model checkpoint and is honored first
model_checkpoint: /blue/ewhite/everglades/Zooniverse//20230426_082328/species_model.pl
test_csv:
images_to_annotate_dir: '/blue/ewhite/everglades/FWSImaging2024/JPG_20240417_UFL'
checkpoint_dir: '/blue/ewhite/everglades/label_studio/FWS/checkpoints'
train_csv_folder: /blue/ewhite/everglades/label_studio/FWS/annotated_images/csvs

# Active learning
annotated_images_dir: '/blue/ewhite/everglades/label_studio/FWS/annotated_images'
annotation_csv:
patch_size: 2000
patch_overlap: 0
min_score: 0.4
pool_limit: 20000
strategy: 'target-labels'
# Number of images to select for annotation
n_images: 100
# Labels to include in the active learning

target_labels:
  - "Roseate Spoonbill"

# Filter labels, use 'None' to include all labels, use blank to have background class with no labels in images
labels:
  - "Great Egret"
  - "Roseate Spoonbill"
  - "White Ibis"
  - "Great Blue Heron"
  - "Wood Stork"
  - "Snowy Egret"
  - "Anhinga"
  - 
# Label studio
label_studio_url: "https://labelstudio.naturecast.org/"
label_studio_project_name: "Fish and Wildlife Everglades Flight"

# Debugging
force_run: True
skip_train: False