# A yaml file that contains the configuration for the pipeline

# Remote server for image hosting
user: 'ben'
host: 'serenity.ifas.ufl.edu'
key_filename: '/home/b.weinstein/.ssh/id_rsa.pub'
folder_name: '/pgsql/retrieverdash/everglades-label-studio/everglades-data'

# Model Training
# Model checkpoints are saved in the checkpoint_dir, model_checkpoint is the path to the model checkpoint and is honored first
model_checkpoint: 'tree'
test_csv: '/orange/idtrees-collab/NeonTreeEvaluation/'
images_to_annotate_dir: '/blue/ewhite/b.weinstein/MillionTrees/images_to_annotate/Restor'
checkpoint_dir: '/blue/ewhite/b.weinstein/MillionTrees/checkpoints'
train_csv_folder: /blue/ewhite/b.weinstein/MillionTrees/annotated_images/csv
labels:
  - 'Tree'
comet_workspace: "bw4sz"
comet_project: "million-trees"

# Active learning
annotated_images_dir: '/blue/ewhite/b.weinstein/MillionTrees/annotated_images'
annotation_csv:
patch_size: 1600
patch_overlap: 0.1
min_score: 0.3
strategy: 'random'

# Labels to include in the active learning
target_labels:
  - "Tree"

# Number of images to select for annotation
n_images: 200

# Label studio
label_studio_url: "https://labelstudio.naturecast.org/"
label_studio_project_name: "MillionTrees"

# Debugging
force_run: True
skip_train: True